config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'books#index'
  resources :books
  resources :bookmarks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: { message: "Title cannot be blank."}, uniqueness: { message: "This book is already on the list."}
  validates :author, presence: { message: "Please fill in the author." }
  has_many :bookmarks, dependent: :destroy
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

before_action :lookfor_book

  def Index
    @bookmarks = Bookmark.all
  end

  def show

  end

  def new
    @bookmark = @book.bookmarks.new
  end

  def edit

  end

  def create
    @bookmark = @book.bookmarks.new(bookmark_params)
    if @bookmark.save
      flash[:success] = "Bookmark is created"
      redirect_to books_path
    else
      flash[:error] = "Bookmark is not saved"
      render :new
    end
  end

  def update

  end

  def destroy


  end

private

  def lookfor_book
    @book = Book.find(params[:book_id])
  end

    def bookmark_params
      params.require(:bookmark).permit(:page_num, :decrip)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
  #ViewCount.create(name: "Index")
    @books = Book.order(:id)
  #create viewcount model and db table
  #save viewcount at controller Action
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to books_path
    else
      render :new
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to books_path
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :genre, :read)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/edit.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h2 class="display-3 text-center">Edit Book Details</h2>

    <div class="card vertical-center" style="width: 40rem;">
      <ul class="list-group">
      <%= simple_form_for @book do |f| %>

      <li class="form-style-2 list-group-item vertical-center text-center"><%= f.input :title %></li>

      <li class="form-style-2 list-group-item vertical-center text-center"><%= f.input :author %></li>

      <li class="form-style-2 list-group-item vertical-center text-center"><%= f.input :genre %></li>

      <li class="card vertical-center">
      <%= f.input :read, as: :boolean, checked_value: true, unchecked_value: false %>
      </li>
      <li class="form-style-2 list-group-item vertical-center text-center"><%= f.button :submit %></li>
      <% end %>

<!--below is done if error message is done outside of the simpleforms-->
      <% @book.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>

      </ul>
    </div>
  </div>


<h3 class="text-center"><%= link_to ' = Go Back to Books = ', books_path %></h3>
</div>

app/views/books/index.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container-fluid">
    <h2 class="display-1 text-center"> <strong>&Bopf;&oopf;&oopf;&kopf;&sopf;</strong></h2>

    <div class="row justify-content-center">
    <table class="table table-bordered table-responsive w-auto">
    <thead>
      <tr>
        <th>No.</th>
        <th>Read?</th>
        <th>Title</th>
        <th>Author</th>
        <th>Genre</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody border="1" >
      <% @books.each do |book| %>
        <tr>
          <td></td>
          <td><%= book.read %></td>
          <td><%= book.title %></td>
          <td><%= book.author %></td>
          <td><%= book.genre %></td>
          <td><%= link_to 'Show Book Details', book_path(book) %></td>
          <td><%= link_to 'Edit Details', edit_book_path(book) %></td>
          <td><%= link_to 'Delete from List', book_path(book), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
    </table>
    </div>

  <br>
      <h3 class="text-center">
        <%= link_to '= Add New Book =', new_book_path %></h3>
  </div>
</div>

app/views/books/new.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-1 text-center"> Add A New book </h1>

    <div class="form-group">
      <ul class="list-group">
      <%= simple_form_for @book, url: books_path do |f| %>
      <li class="form-style-2 vertical-center text-center"><%= f.input :title %></li>
      <li class="form-style-2 vertical-center text-center"><%= f.input :author %></li>

      <li class="form-style-2 vertical-center text-center"><%= f.input :genre %></li>

      <li class="form-style-2 vertical-center text-center"><%= f.button :submit %></li>
      <% end %>


      </ul>
    </div>
  </div>


<h3 class="text-center"><%= link_to '= Return to Books = ', books_path %></h3>
</div>

app/views/books/show.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container-fluid">
    <h2 class="display-1 text-center"><strong>Book Introduction</strong> </h2>


    <h3 class="display-2 text-center"><%= @book.author %> is the author of <%= @book.title %>,it is listed as Book id on your reading list.</h2>

    <ul>
    <%= simple_form_for @book.bookmarks.build, url: bookmarks_path(@book), method: :post do |f| %>
    <li class="form-style-2 vertical-center text-center"><%= f.input :page_num %></li>
    <li class="form-style-2 vertical-center text-center"><%= f.input :decrip %></li>
    <li class="form-style-2 vertical-center text-center"><%= f.button :submit %></li>
    <% end %>
    </ul


<h3 class="text-center"><%= link_to 'Back to Bookshelf', books_path %></h3>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reading List</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <link rel="stylesheet" href="../assets/stylesheets/main.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>